import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('ERROR: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY environment variables must be set.');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  },
});

const TARGET_DIR = path.resolve(__dirname, '../src/question_bank');

// Helper to normalize the category key to filename-safe format
const getCategoryFilename = (catId) => {
  return catId.toLowerCase().replace(/[^a-z0-9_-]/g, '');
};

async function syncData() {
  try {
    console.log('Starting Supabase Database-to-Code Sync...');
    
    // Ensure target directory exists
    if (!fs.existsSync(TARGET_DIR)) {
      fs.mkdirSync(TARGET_DIR, { recursive: true });
    }

    // 1. Fetch and compile Exams
    console.log('Fetching exams from Supabase...');
    const { data: exams, error: examsError } = await supabase
      .from('exams')
      .select('*');

    if (examsError) throw examsError;

    const visibleExams = (exams || []).filter(
      (exam) => exam.status !== 'hidden' && exam.status !== 'unpublished'
    );

    const examsPath = path.join(TARGET_DIR, 'exams.json');
    fs.writeFileSync(examsPath, JSON.stringify(visibleExams, null, 2), 'utf-8');
    console.log(`Successfully compiled ${visibleExams.length} exams into ${examsPath}`);

    // 2. Fetch and compile Questions
    console.log('Fetching published questions from Supabase...');
    const { data: questions, error: questionsError } = await supabase
      .from('questions')
      .select('id, category_id, question, options, correct_id, explanation, difficulty, tags, pyq, created_at')
      .eq('status', 'published')
      .order('created_at', { ascending: false });

    if (questionsError) throw questionsError;

    const questionsList = questions || [];
    console.log(`Fetched ${questionsList.length} published questions.`);

    // Group questions by category_id
    const groupedQuestions = {};
    questionsList.forEach((q) => {
      const catId = q.category_id || 'general';
      if (!groupedQuestions[catId]) {
        groupedQuestions[catId] = [];
      }
      
      // Normalize question object format
      groupedQuestions[catId].push({
        id: q.id,
        category_id: catId,
        tags: Array.isArray(q.tags) ? q.tags : [],
        difficulty: q.difficulty || null,
        question: q.question,
        correctId: q.correct_id || q.correctId || 'a',
        options: Array.isArray(q.options) ? q.options : [],
        explanation: q.explanation || '',
        pyq: q.pyq || null,
        created_at: q.created_at
      });
    });

    // Write category files and compile registry map
    const categoryKeys = Object.keys(groupedQuestions);
    const registryEntries = [];

    categoryKeys.forEach((catId) => {
      const filename = getCategoryFilename(catId);
      const filePath = path.join(TARGET_DIR, `${filename}.json`);
      
      fs.writeFileSync(
        filePath,
        JSON.stringify(groupedQuestions[catId], null, 2),
        'utf-8'
      );
      console.log(`Compiled category "${catId}" -> ${filename}.json (${groupedQuestions[catId].length} questions)`);

      registryEntries.push(`  "${catId}": () => import('./${filename}.json')`);
    });

    // Write registry.js
    const registryContent = `// Automatically generated by scripts/sync_data.js. Do not edit manually.
export const CATEGORY_LOADERS = {
${registryEntries.join(',\n')}
};
`;
    const registryPath = path.join(TARGET_DIR, 'registry.js');
    fs.writeFileSync(registryPath, registryContent, 'utf-8');
    console.log(`Successfully generated dynamic import registry at ${registryPath}`);

    console.log('Database-to-Code sync completed successfully.');
  } catch (err) {
    console.error('Fatal sync error:', err);
    process.exit(1);
  }
}

syncData();
