// Automatically generated by scripts/sync_data.js. Do not edit manually.
export const CATEGORY_LOADERS = {
  "indian-economy": () => import('./indian-economy.json'),
  "general-science": () => import('./general-science.json'),
  "indian-polity": () => import('./indian-polity.json'),
  "jk-affairs": () => import('./jk-affairs.json')
};
