// Automatically generated by scripts/sync_data.js. Do not edit manually.
export const WEEKLY_TEST_LOADERS = {
  "jkssb-faa-weekly-mtcz05ia": () => import('./weekly_tests/jkssb-faa-weekly-mtcz05ia.json')
};
