// Automatically generated by scripts/sync_data.js. Do not edit manually.
export const WEEKLY_TEST_LOADERS = {
  "jkssb-faa-weekly-mtcm6enf": () => import('./weekly_tests/jkssb-faa-weekly-mtcm6enf.json'),
  "jkssb-faa-weekly-mtcl1an9": () => import('./weekly_tests/jkssb-faa-weekly-mtcl1an9.json')
};
